Update patch set 4
Patch Set 4:

Hmm... ran the archetype with (after building it from this gerrit rebased onto master):

mvn archetype:generate -DarchetypeGroupId=org.opendaylight.toolkit  -DarchetypeArtifactId=md-sal-app-simple -DarchetypeVersion=1.0-SNAPSHOT

Manually provided:

Define value for property 'groupId': : org.opendaylight.ofextensions
Define value for property 'artifactId': : regload
Define value for property 'version':  1.0-SNAPSHOT: : 1.0.0-SNAPSHOT
Define value for property 'package':  org.opendaylight.ofextensions: : 
[INFO] Using property: appName = task
[INFO] Using property: modelFields = {"title":"string", "desc":"string"}
Confirm properties configuration:
groupId: org.opendaylight.ofextensions
artifactId: regload
version: 1.0.0-SNAPSHOT
package: org.opendaylight.ofextensions
appName: task
modelFields: {"title":"string", "desc":"string"}
 Y: : 

cd regload
mvn clean install -Dgen

fails with error:

[ERROR] yang-to-sources: Unable to parse yang files from /Users/hagbard/archetypeattempts/regload/model/src/main/yang
java.io.FileNotFoundException: /Users/hagbard/archetypeattempts/regload/model/src/main/yang
	at org.opendaylight.yangtools.yang2sources.plugin.Util.listFiles(Util.java:85)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.processYang(YangToSourcesProcessor.java:100)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.execute(YangToSourcesProcessor.java:83)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesMojo.execute(YangToSourcesMojo.java:122)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] regload ........................................... SUCCESS [0.310s]
[INFO] regload-model ..................................... FAILURE [1.213s]
[INFO] regload-provider .................................. SKIPPED
[INFO] regload-consumer .................................. SKIPPED
[INFO] regload-web ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.216s
[INFO] Finished at: Sun Jul 06 10:56:00 CDT 2014
[INFO] Final Memory: 12M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.opendaylight.yangtools:yang-maven-plugin:0.6.2-SNAPSHOT:generate-sources (default) on project regload-model: yang-to-sources: Unable to parse yang files from /Users/hagbard/archetypeattempts/regload/model/src/main/yang -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :regload-model

Now... admittedly I have no model yet... but that seems a bit unfriendly :(

Would it be possible to get a simple starter model in there?

Patch-set: 4
Reviewer: Gerrit User 9 <9@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0